#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=*
info.app.name=config-server
info.app.description=Config-server Application built by Mohamed
info.app.version=1.0.0
