#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#management.endpoints.web.exposure.include=*
info.app.name=Gatewaynouv
info.app.description=Gatewaynouv Application built by Mohamed
info.app.version=1.0.0
