spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: companyms-service
              uri: ${COMPANYMS_SERVICE_URL:http://localhost:8068}
#              uri: ${COMPANYMS_SERVICE_URL:lb://COMPANYMS-SERVICE}
              predicates:
                - Path=/company/**
              filters:
                  - RewritePath=/company/?(?<segment>.*),/${segment}
            - id: jobsms-service
              uri: ${JOBMS_SERVICE_URL:http://localhost:8067}
#              uri: ${JOBMS_SERVICE_URL:lb://JOBMS-SERVICE}
              predicates:
                - Path=/job/**
              filters:
                - RewritePath=/job/?(?<segment>.*),/${segment}
            - id: reviewms-service
              uri: ${REVIEWMS_SERVICE_URL:http://localhost:8069}
#              uri: ${REVIEWMS_SERVICE_URL:lb://REVIEWMS-SERVICE}
              predicates:
                - Path=/review/**
              filters:
                - RewritePath=/review/?(?<segment>.*),/${segment}
            - id: gatewaynouv-service
              uri: ${GATEWAYNOUV_SERVICE_URL:http://localhost:8761}
              predicates:
                - Path=/eureka/main
              filters:
                - SetPath=/
            - id: eureka-server-static
              uri: ${GATEWAYNOUV_SERVICE_URL:http://localhost:8761}
              predicates:
                - Path=/eureka/**
        discovery:
          locator:
            enabled: true
  mvc:
    problemedetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
#        include: "*"
        include: gateway
  info:
    env:
      enabled: true
  endpoint:
    gateway:
#      enabled: true
      access: read-only


info:
  app:
    name: "gatewaynouv-service"
    description: "This is api gateway"
    version: "1.0"
